---
name: Test

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          push: false
          tags: kabakaev/smtp-relay:testing
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
